[package]
name = "rust-roguelike"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bracket-lib = "0.8.7"
num_enum = "0.7.2"
once_cell = "1.19.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
rusqlite = { version = "0.32.1", features = ["bundled-full"] }
