[package]
name = "rust-roguelike"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bracket-lib = "0.8.7"
num_enum = "0.7.2"
rusqlite = { version = "0.31.0", features = ["bundled"] }
